from flask import Flask
from flask import request
from flask import jsonify

from peewee import *
from playhouse.shortcuts import model_to_dict

db = PostgresqlDatabase('game', user='postgres', password='', host='localhost', port=5432)

class BaseModel(Model):
    class Meta:
        database = db

class Games(BaseModel):
    name = CharField()
    sales = IntegerField()
    release = CharField()
    genre = CharField()
    developer = CharField()
    publisher = CharField()
    


db.connect()
db.drop_tables([Games])
db.create_tables([Games])

GAMES1 = Games(name="PlayerUnknown's Battlegrounds", sales=42, release="Dec-17", genre="Battle royale", developer="PUBG Studios", publisher="Krafton")
GAMES2 = Games(name="Minecraft", sales=33, release="Nov-11", genre="Sandbox, survival", developer="Mojang Studios", publisher="Mojang Studios")
GAMES3 = Games(name="Diablo III", sales=20, release="May-12", genre="Action role-playing", developer="Blizzard Entertainment", publisher="Blizzard Entertainment")
GAMES4 = Games(name="Garry's Mod", sales=20, release="Nov-06", genre="Sandbox", developer="Facepunch Studios", publisher="Valve")
GAMES5 = Games(name="Terraria", sales=17.2, release="May-11", genre="Action-adventure", developer="Re-Logic", publisher="Re-Logic")
GAMES6 = Games(name="World of Warcraft", sales=14, release="Nov-04", genre="MMORPG", developer="Blizzard Entertainment", publisher="Blizzard Entertainment")
GAMES7 = Games(name="Half-Life 2", sales=12, release="Nov-04", genre="First-person shooter", developer="Valve", publisher="Valve (digital)")
GAMES8 = Games(name="The Witcher 3: Wild Hunt", sales=12, release="May-15", genre="Action role-playing", developer="CD Projekt Red", publisher="CD Projekt")
GAMES9 = Games(name="StarCraft", sales=11, release="Mar-98", genre="Real-time strategy", developer="Blizzard Entertainment", publisher="Blizzard Entertainment")
GAMES10 = Games(name="The Sims", sales=11, release="Feb-00", genre="Life simulation", developer="Maxis", publisher="Electronic Arts")
GAMES11 = Games(name="Fall Guys", sales=10, release="Aug-20", genre="Battle royale", developer="Mediatonic", publisher="Devolver Digital")
GAMES12 = Games(name="RollerCoaster Tycoon 3", sales=10, release="Oct-04", genre="Construction and management simulation", developer="Frontier Developments", publisher="Atari, Inc. (Windows)")
GAMES13 = Games(name="Half-Life", sales=9, release="Nov-98", genre="First-person shooter", developer="Valve", publisher="Sierra Entertainment")
GAMES14 = Games(name="Rust", sales=9, release="Feb-18", genre="Survival", developer="Facepunch Studios", publisher="Facepunch Studios")
GAMES15 = Games(name="Civilization V", sales=8, release="Sep-10", genre="Turn-based strategy, 4X", developer="Firaxis Games", publisher="2K Games & Aspyr")
GAMES16 = Games(name="The Sims 3", sales=7, release="Jun-09", genre="Life simulation", developer="Maxis", publisher="Electronic Arts")
GAMES17 = Games(name="Euro Truck Simulator 2", sales=6.5, release="Oct-12", genre="Vehicle simulation", developer="SCS Software", publisher="SCS Software")
GAMES18 = Games(name="Guild Wars", sales=6, release="Apr-05", genre="MMORPG", developer="ArenaNet", publisher="NCsoft")
GAMES19 = Games(name="StarCraft II: Wings of Liberty", sales=6, release="Jul-10", genre="Real-time strategy", developer="Blizzard Entertainment", publisher="Blizzard Entertainment")
GAMES20 = Games(name="The Sims 2", sales=6, release="Sep-04", genre="Life simulation", developer="Maxis", publisher="Electronic Arts")
GAMES21 = Games(name="Valheim", sales=6, release="Feb-21", genre="Survival", developer="Iron Gate", publisher="Coffee Stain Publishing")
GAMES22 = Games(name="ARMA 3", sales=5.5, release="Sep-13", genre="Tactical shooter", developer="Bohemia Interactive", publisher="Bohemia Interactive")
GAMES23 = Games(name="Last Ninja 2", sales=5.5, release="Aug-88", genre="Action-adventure", developer="System 3", publisher="Activision")
GAMES24 = Games(name="Cities: Skylines", sales=5, release="Mar-15", genre="City-building", developer="Colossal Order", publisher="Paradox Interactive")
GAMES25 = Games(name="Guild Wars 2", sales=5, release="Aug-12", genre="MMORPG", developer="ArenaNet", publisher="NCsoft")
GAMES26 = Games(name="SimCity 3000", sales=5, release="Jan-99", genre="City-building", developer="Maxis", publisher="Electronic Arts")
GAMES27 = Games(name="The Forest", sales=5, release="Apr-18", genre="Survival", developer="Endnight Games", publisher="Endnight Games")
GAMES28 = Games(name="Cyberpunk 2077", sales=4.5, release="Dec-20", genre="Action role-playing", developer="CD Projekt Red", publisher="CD Projekt")
GAMES29 = Games(name="DayZ", sales=4, release="Dec-13", genre="Survival", developer="Bohemia Interactive", publisher="Bohemia Interactive")
GAMES30 = Games(name="Diablo II", sales=4, release="Jun-00", genre="Action role-playing", developer="Blizzard North", publisher="Blizzard Entertainment")
GAMES31 = Games(name="Populous", sales=4, release="Jun-89", genre="God game", developer="Bullfrog Productions", publisher="Electronic Arts")
GAMES32 = Games(name="RollerCoaster Tycoon", sales=4, release="Mar-99", genre="Construction and management simulation", developer="Chris Sawyer", publisher="MicroProse Software")
GAMES33 = Games(name="The Last Ninja", sales=4, release="Jun-05", genre="Action-adventure", developer="System 3", publisher="Activision")
GAMES34 = Games(name="Warhammer 40,000: Dawn of War (including expansions)", sales=4, release="Sep-04", genre="Real-time strategy", developer="Relic Entertainment", publisher="THQ")
GAMES35 = Games(name="Where in the World Is Carmen Sandiego?", sales=4, release="Jun-85", genre="Educational", developer="Broderbund", publisher="Broderbund")
GAMES36 = Games(name="Dark Souls", sales=3.6, release="Aug-12", genre="Action role-playing", developer="FromSoftware", publisher="Namco Bandai Games")
GAMES37 = Games(name="Dark Souls III", sales=3.3, release="Apr-16", genre="Action role-playing", developer="FromSoftware", publisher="Bandai Namco Entertainment")
GAMES38 = Games(name="Age of Empires", sales=3, release="Oct-97", genre="Real-time strategy", developer="Ensemble Studios", publisher="Microsoft")
GAMES39 = Games(name="Civilization IV", sales=3, release="Oct-05", genre="Turn-based strategy, 4X", developer="Firaxis Games", publisher="2K Games & Aspyr")
GAMES40 = Games(name="Command & Conquer", sales=3, release="Aug-95", genre="Real-time strategy", developer="Westwood Studios", publisher="Virgin Interactive")
GAMES41 = Games(name="Command & Conquer: Red Alert", sales=3, release="Oct-96", genre="Real-time strategy", developer="Westwood Studios", publisher="Virgin Interactive")
GAMES42 = Games(name="Crysis", sales=3, release="Nov-07", genre="First-person shooter", developer="Crytek", publisher="Electronic Arts")
GAMES43 = Games(name="EverQuest", sales=3, release="Mar-99", genre="MMORPG", developer="Verant Interactive", publisher="Sony Online Entertainment")
GAMES44 = Games(name="Life Is Strange", sales=3, release="Jan-15", genre="Graphic adventure", developer="Dontnod Entertainment", publisher="Square Enix")
GAMES45 = Games(name="Theme Park", sales=3, release="Jun-05", genre="Construction and management simulation", developer="Bullfrog Productions", publisher="Electronic Arts")
GAMES46 = Games(name="Warcraft III: Reign of Chaos", sales=3, release="Jul-02", genre="Real-time strategy", developer="Blizzard Entertainment", publisher="Blizzard Entertainment (North America)")
GAMES47 = Games(name="Dark Souls II", sales=2.7, release="Apr-14", genre="Action role-playing", developer="FromSoftware", publisher="Bandai Namco Games")
GAMES48 = Games(name="Caesar II", sales=2.5, release="Sep-95", genre="City-building game", developer="Impressions Game", publisher="Sierra On-Line")
GAMES49 = Games(name="Caesar III", sales=2.5, release="May-99", genre="City-building game", developer="Impressions Game", publisher="Sierra Studios")
GAMES50 = Games(name="Factorio", sales=2.5, release="Feb-16", genre="Construction and management simulation", developer="Wube Software", publisher="Wube Software")
GAMES51 = Games(name="Lords of the Realm II", sales=2.5, release="Oct-96", genre="Turn-based strategy", developer="Impressions Game", publisher="Impressions Game")
GAMES52 = Games(name="Myst", sales=2.5, release="Sep-93", genre="Adventure, puzzle", developer="Cyan", publisher="Brøderbund")
GAMES53 = Games(name="Final Fantasy VII", sales=2.1, release="Jun-98", genre="Role-playing game", developer="Square", publisher="Eidos Interactive")
GAMES54 = Games(name="7 Days to Die", sales=2, release="Jun-16", genre="Survival horror", developer="The Fun Pimps", publisher="The Fun Pimps")
GAMES55 = Games(name="Age of Empires II: The Age of Kings", sales=2, release="Sep-99", genre="Real-time strategy", developer="Ensemble Studios", publisher="Microsoft")
GAMES56 = Games(name="Age of Empires III", sales=2, release="Oct-05", genre="Real-time strategy", developer="Ensemble Studios", publisher="Microsoft")
GAMES57 = Games(name="Anno 1503", sales=2, release="Mar-03", genre="City-building", developer="Max Design", publisher="Sunflowers")
GAMES58 = Games(name="Anno 1602", sales=2, release="Sep-98", genre="City-building", developer="Max Design", publisher="Sunflowers")
GAMES59 = Games(name="Baldur's Gate", sales=2, release="Dec-98", genre="Role-playing game", developer="BioWare", publisher="Interplay Entertainment")
GAMES60 = Games(name="Baldur's Gate II: Shadows of Amn", sales=2, release="Sep-00", genre="Computer role-playing game", developer="BioWare", publisher="Interplay Entertainment")
GAMES61 = Games(name="Battlefield 1942", sales=2, release="Sep-02", genre="First-person shooter", developer="EA DICE", publisher="Electronic Arts")
GAMES62 = Games(name="Black & White", sales=2, release="Mar-01", genre="God game", developer="Lionhead Studios", publisher="EA Games")
GAMES63 = Games(name="Civilization III", sales=2, release="Oct-01", genre="Turn-based strategy, 4X", developer="Firaxis Games", publisher="Infogrames")
GAMES64 = Games(name="Cossacks II: Napoleonic Wars", sales=2, release="Apr-05", genre="Real-time strategy", developer="GSC Game World", publisher="CDV Software")
GAMES65 = Games(name="Counter-Strike: Condition Zero", sales=2, release="Mar-04", genre="First-person shooter", developer="Valve", publisher="Valve (digital)")
GAMES66 = Games(name="Counter-Strike: Source", sales=2, release="Nov-04", genre="First-person shooter", developer="Valve", publisher="Electronic Arts (retail)")
GAMES67 = Games(name="Diablo", sales=2, release="Dec-96", genre="Action role-playing", developer="Blizzard North", publisher="Blizzard Entertainment (North America)")
GAMES68 = Games(name="Doom", sales=2, release="Dec-93", genre="First-person shooter", developer="id Software", publisher="id Software")
GAMES69 = Games(name="Doom II: Hell on Earth", sales=2, release="Sep-94", genre="First-person shooter", developer="id Software", publisher="GT Interactive")
GAMES70 = Games(name="Far Cry", sales=2, release="Mar-04", genre="First-person shooter", developer="Crytek", publisher="Ubisoft")
GAMES71 = Games(name="Grand Theft Auto V", sales=2, release="Apr-15", genre="Action-adventure", developer="Rockstar North", publisher="Rockstar Games")
GAMES72 = Games(name="Mafia: The City of Lost Heaven", sales=2, release="Aug-02", genre="Third-person shooter", developer="Illusion Softworks", publisher="Gathering of Developers")
GAMES73 = Games(name="Magicka", sales=2, release="Jan-11", genre="Action-adventure", developer="Arrowhead Game Studios", publisher="Paradox Interactive")
GAMES74 = Games(name="Neverwinter Nights", sales=2, release="Jun-02", genre="Role-playing game", developer="BioWare", publisher="Infogrames / Atari")
GAMES75 = Games(name="Planet Coaster", sales=2, release="Nov-16", genre="Construction and management simulation", developer="Frontier Developments", publisher="Frontier Developments")
GAMES76 = Games(name="POD", sales=2, release="Feb-97", genre="Racing game", developer="Ubisoft", publisher="Ubisoft")
GAMES77 = Games(name="SimCity", sales=2, release="Mar-13", genre="City-building", developer="Electronic Arts", publisher="Electronic Arts")
GAMES78 = Games(name="SimCity 4", sales=2, release="Jan-03", genre="City-building", developer="Maxis", publisher="Electronic Arts (Windows)")
GAMES79 = Games(name="Space Engineers", sales=2, release="Oct-13", genre="Simulation", developer="Keen Software House", publisher="Keen Software House")
GAMES80 = Games(name="Spore", sales=2, release="Sep-08", genre="God game", developer="Maxis", publisher="Electronic Arts")
GAMES81 = Games(name="Stickfight: The Game", sales=2, release="Sep-17", genre="Fighting", developer="Landfall Games", publisher="Landfall Games")
GAMES82 = Games(name="Stronghold: Crusader", sales=2, release="Jul-02", genre="Real-time strategy", developer="Firefly Studios", publisher="Take-Two Interactive / Gathering of Developers")
GAMES83 = Games(name="The Binding of Isaac", sales=2, release="Sep-11", genre="Action-adventure, roguelike", developer="Edmund McMillen & Florian Himsl", publisher="Headup Games")
GAMES84 = Games(name="The Witcher", sales=2, release="Oct-07", genre="Action role-playing", developer="CD Projekt Red", publisher="Atari, Inc")
GAMES85 = Games(name="The Witcher 2: Assassins of Kings", sales=2, release="May-11", genre="Action role-playing", developer="CD Projekt Red", publisher="CD Projekt")
GAMES86 = Games(name="Warcraft II: Tides of Darkness", sales=2, release="Dec-95", genre="Real-time strategy", developer="Blizzard Entertainment", publisher="Blizzard Entertainment")
GAMES87 = Games(name="Metal Gear Solid V: The Phantom Pain", sales=1.8, release="Sep-15", genre="Action-adventure, stealth", developer="Kojima Productions", publisher="Konami")
GAMES88 = Games(name="American Truck Simulator", sales=1.5, release="Oct-12", genre="Vehicle simulation", developer="SCS Software", publisher="SCS Software")
GAMES89 = Games(name="International Karate", sales=1.5, release="Nov-85", genre="Fighting", developer="System 3", publisher="Epyx")
GAMES90 = Games(name="Sega Mega Drive and Genesis Classics", sales=1.5, release="Jun-10", genre="Compilation", developer="Sega", publisher="Sega")
GAMES91 = Games(name="Stellaris", sales=1.5, release="May-16", genre="RTS, 4X, Grand Strategy", developer="Paradox Development Studio", publisher="Paradox Interactive")
GAMES92 = Games(name="Resident Evil 6", sales=1.3, release="Mar-13", genre="Third-person shooter, survival horror", developer="Capcom", publisher="Capcom")
GAMES93 = Games(name="Satisfactory", sales=1.3, release="Mar-19", genre="Construction and management simulation", developer="Coffee Stain Studios", publisher="Coffee Stain Publishing")
GAMES94 = Games(name="Ultra Street Fighter IV", sales=1.3, release="Jul-09", genre="Fighting", developer="Capcom", publisher="Capcom")
GAMES95 = Games(name="Nier: Automata", sales=1.2, release="Mar-17", genre="Action role-playing, hack and slash", developer="PlatinumGames", publisher="Square Enix")
GAMES96 = Games(name="Resident Evil 4: Ultimate HD Edition", sales=1.2, release="Feb-14", genre="Third-person shooter, survival horror", developer="Capcom", publisher="Capcom")
GAMES97 = Games(name="Kingdom Come: Deliverance", sales=1.1, release="Feb-18", genre="Action role-playing game", developer="Warhorse Studios", publisher="Warhorse Studios")
GAMES98 = Games(name="Pac-Man Championship Edition DX+", sales=1.1, release="Sep-13", genre="Maze, arcade", developer="Namco Bandai Games", publisher="Namco Bandai Games")
GAMES99 = Games(name="Age of Mythology", sales=1, release="Oct-02", genre="Real-time strategy", developer="Ensemble Studios", publisher="Microsoft")
GAMES100 = Games(name="American McGee's Alice", sales=1, release="Oct-00", genre="Action-adventure, platformer", developer="Rogue Entertainment", publisher="Electronic Arts")
GAMES101 = Games(name="Ark: Survival Evolved", sales=1, release="Jun-15", genre="Action-adventure, Survival", developer="Studio Wildcard", publisher="Studio Wildcard")
GAMES102 = Games(name="Battlefield Vietnam", sales=1, release="Mar-04", genre="First-person shooter", developer="EA DICE", publisher="Electronic Arts")
GAMES103 = Games(name="BioShock", sales=1, release="Aug-07", genre="First-person shooter", developer="Irrational Games", publisher="2K Games")
GAMES104 = Games(name="Blade Runner", sales=1, release="Nov-97", genre="Point-and-click", developer="Westwood Studios", publisher="Virgin Interactive")
GAMES105 = Games(name="Civilization II", sales=1, release="Feb-96", genre="Turn-based strategy, 4X", developer="MicroProse", publisher="MicroProse")
GAMES106 = Games(name="Command & Conquer 3: Tiberium Wars", sales=1, release="Mar-07", genre="Real-time strategy", developer="EA Los Angeles", publisher="Electronic Arts")
GAMES107 = Games(name="Command & Conquer: Red Alert 2", sales=1, release="Oct-00", genre="Real-time strategy", developer="Westwood Pacific", publisher="Electronic Arts")
GAMES108 = Games(name="Command & Conquer: Tiberian Sun", sales=1, release="Aug-99", genre="Real-time strategy", developer="Westwood Studios", publisher="Electronic Arts")
GAMES109 = Games(name="Commandos: Behind Enemy Lines", sales=1, release="Jun-98", genre="Real-time tactics", developer="Pyro Studios", publisher="Eidos Interactive")
GAMES110 = Games(name="Crusader Kings II", sales=1, release="Feb-12", genre="Grand strategy", developer="Paradox Development Studio", publisher="Paradox Interactive")
GAMES111 = Games(name="Crusader Kings III", sales=1, release="Sep-20", genre="Grand strategy", developer="Paradox Development Studio", publisher="Paradox Interactive")
GAMES112 = Games(name="Crysis Warhead", sales=1, release="Sep-08", genre="First-person shooter", developer="Crytek Budapest", publisher="Electronic Arts")
GAMES113 = Games(name="Cuphead", sales=1, release="Sep-17", genre="Run and gun", developer="StudioMDHR", publisher="StudioMDHR")
GAMES114 = Games(name="Danganronpa 2: Goodbye Despair", sales=1, release="Apr-16", genre="Visual novel, adventure", developer="Spike Chunsoft", publisher="Spike Chunsoft")
GAMES115 = Games(name="Danganronpa: Trigger Happy Havoc", sales=1, release="Feb-16", genre="Visual novel, adventure", developer="Spike Chunsoft", publisher="Spike Chunsoft")
GAMES116 = Games(name="Daryl F. Gates' Police Quest: SWAT", sales=1, release="Sep-95", genre="Interactive movie", developer="Sierra Online", publisher="Sierra Online")
GAMES117 = Games(name="Deer Hunter", sales=1, release="Nov-97", genre="Sports", developer="Sunstorm Interactive", publisher="WizardWorks")
GAMES118 = Games(name="Divinity: Original Sin II", sales=1, release="Sep-17", genre="Role-playing game", developer="Larian Studios", publisher="Larian Studios")
GAMES119 = Games(name="Duke Nukem 3D", sales=1, release="Jan-96", genre="First-person shooter", developer="3D Realms", publisher="GT Interactive Software")
GAMES120 = Games(name="Dungeon Lords", sales=1, release="May-05", genre="Role-playing game", developer="Heuristic Park", publisher="DreamCatcher Interactive")
GAMES121 = Games(name="Dungeon Siege", sales=1, release="Apr-02", genre="Role-playing game", developer="Gas Powered Games", publisher="Microsoft Game Studios")
GAMES122 = Games(name="Empire Earth", sales=1, release="Nov-01", genre="Real-time strategy", developer="Stainless Steel Studios", publisher="Sierra Entertainment")
GAMES123 = Games(name="Europa Universalis IV", sales=1, release="Aug-13", genre="Grand strategy", developer="Paradox Development Studio", publisher="Paradox Interactive")
GAMES124 = Games(name="Frogger", sales=1, release="Nov-97", genre="Action", developer="SCE Cambridge Studio", publisher="Hasbro Interactive")
GAMES125 = Games(name="Full Throttle", sales=1, release="Apr-95", genre="Graphic adventure", developer="LucasArts", publisher="LucasArts")
GAMES126 = Games(name="Glory of the Roman Empire", sales=1, release="Jun-06", genre="City-building game", developer="Haemimont Games", publisher="CDV Software")
GAMES127 = Games(name="Grand Prix 2", sales=1, release="Aug-96", genre="Sim racing", developer="MicroProse", publisher="MicroProse")
GAMES128 = Games(name="Harry Potter and the Philosopher's Stone", sales=1, release="Nov-01", genre="Action-adventure", developer="KnowWonder", publisher="Electronic Arts")
GAMES129 = Games(name="Hearts of Iron IV", sales=1, release="Jun-16", genre="Real-time strategy, grand strategy wargame", developer="Paradox Development Studio", publisher="Paradox Interactive")
GAMES130 = Games(name="Hidden & Dangerous", sales=1, release="Jul-99", genre="Action", developer="Illusion Softworks", publisher="Take-Two Interactive")
GAMES131 = Games(name="Hidden & Dangerous 2", sales=1, release="Oct-03", genre="Action", developer="Illusion Softworks", publisher="Take-Two Interactive")
GAMES132 = Games(name="Hollow Knight", sales=1, release="Feb-17", genre="Metroidvania", developer="Team Cherry", publisher="Team Cherry")
GAMES133 = Games(name="Hotel Giant", sales=1, release="May-02", genre="Business simulation", developer="Enlight Software", publisher="JoWood Productions")
GAMES134 = Games(name="Hydlide", sales=1, release="Dec-84", genre="Action role-playing", developer="Technology and Entertainment Software", publisher="Technology and Entertainment Software")
GAMES135 = Games(name="Imperivm: Great Battles of Rome", sales=1, release="May-05", genre="Real-time strategy", developer="Haemimont Games", publisher="FX Interactive")
GAMES136 = Games(name="Just Survive[e]", sales=1, release="Jan-15", genre="Survival", developer="Daybreak Game Company", publisher="Daybreak Game Company")
GAMES137 = Games(name="Killing Floor", sales=1, release="May-09", genre="First-person shooter", developer="Tripwire Interactive", publisher="Tripwire Interactive")
GAMES138 = Games(name="Machinarium", sales=1, release="Oct-09", genre="Graphic adventure, puzzle", developer="Amanita Design", publisher="Amanita Design")
GAMES139 = Games(name="Microsoft Flight Simulator X", sales=1, release="Oct-06", genre="Amateur flight simulation", developer="Microsoft Game Studios", publisher="Microsoft Game Studios")
GAMES140 = Games(name="Mordhau", sales=1, release="Apr-19", genre="Action", developer="Triternion", publisher="Triternion")
GAMES141 = Games(name="Operation Flashpoint: Cold War Crisis", sales=1, release="Jun-01", genre="Tactical shooter", developer="Bohemia Interactive Studio", publisher="Codemasters")
GAMES142 = Games(name="Patrician III: Rise of the Hanse", sales=1, release="Oct-03", genre="Business simulation", developer="Ascaron", publisher="Encore")
GAMES143 = Games(name="Phantasmagoria", sales=1, release="Jul-95", genre="Interactive movie", developer="Sierra Online", publisher="Sierra Online")
GAMES144 = Games(name="Prison Architect", sales=1, release="Sep-12", genre="Construction and management simulation", developer="Introversion Software", publisher="Introversion Software")
GAMES145 = Games(name="Psychonauts", sales=1, release="Apr-05", genre="Platform", developer="Double Fine Productions", publisher="THQ")
GAMES146 = Games(name="Quake", sales=1, release="Jun-96", genre="First-person shooter", developer="id Software", publisher="GT Interactive")
GAMES147 = Games(name="Quake II", sales=1, release="Dec-97", genre="First-person shooter", developer="id Software", publisher="Activision")
GAMES148 = Games(name="Railroad Tycoon II", sales=1, release="Nov-98", genre="Construction and management simulation", developer="PopTop Software", publisher="Gathering of Developers")
GAMES149 = Games(name="Resident Evil 5", sales=1, release="Sep-09", genre="Third-person shooter, survival horror", developer="Capcom", publisher="Capcom")
GAMES150 = Games(name="Return to Castle Wolfenstein", sales=1, release="Nov-01", genre="First-person shooter", developer="Gray Matter Interactive", publisher="Activision")
GAMES151 = Games(name="Return to Zork", sales=1, release="Aug-93", genre="Adventure", developer="Infocom", publisher="Activision")
GAMES152 = Games(name="RoboCop", sales=1, release="Dec-88", genre="Beat 'em up, run-and-gun", developer="Data East", publisher="Data East, Ocean Software")
GAMES153 = Games(name="Rome: Total War", sales=1, release="Sep-04", genre="Real-time strategy", developer="The Creative Assembly", publisher="Activision")
GAMES154 = Games(name="Runaway: A Road Adventure", sales=1, release="Jul-01", genre="Adventure", developer="Péndulo Studios, S.L.", publisher="Dinamic Multimedia")
GAMES155 = Games(name="Sacred", sales=1, release="Mar-04", genre="Action role-playing", developer="Ascaron", publisher="Encore")
GAMES156 = Games(name="Star Wars Galaxies", sales=1, release="Jun-03", genre="MMORPG", developer="Sony Online Entertainment", publisher="LucasArts")
GAMES157 = Games(name="Star Wars: Rebel Assault", sales=1, release="Nov-93", genre="Rail shooter", developer="LucasArts", publisher="LucasArts")
GAMES158 = Games(name="StarCraft II: Heart of the Swarm", sales=1, release="Mar-13", genre="Real-time strategy", developer="Blizzard Entertainment", publisher="Blizzard Entertainment")
GAMES159 = Games(name="StarCraft II: Legacy of the Void", sales=1, release="Nov-15", genre="Real-time strategy", developer="Blizzard Entertainment", publisher="Blizzard Entertainment")
GAMES160 = Games(name="Stardew Valley", sales=1, release="Feb-16", genre="Simulation, role-playing game", developer="ConcernedApe", publisher="ConcernedApe[f]")
GAMES161 = Games(name="Stronghold", sales=1, release="Oct-01", genre="Real-time strategy", developer="Firefly Studios", publisher="Take-Two Interactive / Gathering of Developers")
GAMES162 = Games(name="Supreme Commander", sales=1, release="Feb-07", genre="Real-time strategy", developer="Gas Powered Games", publisher="THQ")
GAMES163 = Games(name="Tetris", sales=1, release="Jan-88", genre="Puzzle", developer="Spectrum HoloByte", publisher="Spectrum HoloByte")
GAMES164 = Games(name="The Legend of Sword and Fairy 3", sales=1, release="Jul-03", genre="Role-playing game", developer="Softstar Entertainment", publisher="Softstar Entertainment")
GAMES165 = Games(name="The Legend of Sword and Fairy 5", sales=1, release="Jul-11", genre="Role-playing game", developer="Softstar", publisher="Softstar")
GAMES166 = Games(name="The Stanley Parable", sales=1, release="Oct-13", genre="Interactive fiction", developer="Galactic Cafe", publisher="Galactic Cafe")
GAMES167 = Games(name="Total Annihilation", sales=1, release="Sep-97", genre="Real-time strategy", developer="Cavedog Entertainment", publisher="GT Interactive")
GAMES168 = Games(name="Tropico", sales=1, release="Apr-01", genre="Construction and management simulation", developer="PopTop Software", publisher="Gathering of Developers")
GAMES169 = Games(name="Unreal", sales=1, release="May-98", genre="First-person shooter", developer="Epic Games", publisher="GT Interactive")
GAMES170 = Games(name="Unreal Tournament", sales=1, release="Nov-99", genre="First-person shooter", developer="Epic Games", publisher="GT Interactive")
GAMES171 = Games(name="Vietcong", sales=1, release="Mar-03", genre="Tactical shooter", developer="Pterodon", publisher="Gathering of Developers")
GAMES172 = Games(name="Warhammer Online: Age of Reckoning", sales=1, release="Sep-08", genre="MMORPG", developer="Mythic Entertainment", publisher="Electronic Arts")
GAMES173 = Games(name="Who Wants to Be a Millionaire?", sales=1, release="Nov-99", genre="Trivia game", developer="Jellyvision", publisher="Disney Interactive Studios")
GAMES174 = Games(name="Wing Commander 3: Heart of the Tiger", sales=1, release="Dec-94", genre="Space combat simulation", developer="Origin Systems", publisher="Electronic Arts")
GAMES175 = Games(name="Zoo Tycoon", sales=1, release="Oct-01", genre="Business simulation", developer="Microsoft", publisher="Blue Fang Games")




GAMES1.save() 
GAMES2.save() 
GAMES3.save() 
GAMES4.save() 
GAMES5.save() 
GAMES6.save() 
GAMES7.save() 
GAMES8.save() 
GAMES9.save() 
GAMES10.save() 
GAMES11.save() 
GAMES12.save() 
GAMES13.save() 
GAMES14.save() 
GAMES15.save() 
GAMES16.save() 
GAMES17.save() 
GAMES18.save() 
GAMES19.save() 
GAMES20.save() 
GAMES21.save() 
GAMES22.save() 
GAMES23.save() 
GAMES24.save() 
GAMES25.save() 
GAMES26.save() 
GAMES27.save() 
GAMES28.save() 
GAMES29.save() 
GAMES30.save() 
GAMES31.save() 
GAMES32.save() 
GAMES33.save() 
GAMES34.save() 
GAMES35.save() 
GAMES36.save() 
GAMES37.save() 
GAMES38.save() 
GAMES39.save() 
GAMES40.save() 
GAMES41.save() 
GAMES42.save() 
GAMES43.save() 
GAMES44.save() 
GAMES45.save() 
GAMES46.save() 
GAMES47.save() 
GAMES48.save() 
GAMES49.save() 
GAMES50.save() 
GAMES51.save() 
GAMES52.save() 
GAMES53.save() 
GAMES54.save() 
GAMES55.save() 
GAMES56.save() 
GAMES57.save() 
GAMES58.save() 
GAMES59.save() 
GAMES60.save() 
GAMES61.save() 
GAMES62.save() 
GAMES63.save() 
GAMES64.save() 
GAMES65.save() 
GAMES66.save() 
GAMES67.save() 
GAMES68.save() 
GAMES69.save() 
GAMES70.save() 
GAMES71.save() 
GAMES72.save() 
GAMES73.save() 
GAMES74.save() 
GAMES75.save() 
GAMES76.save() 
GAMES77.save() 
GAMES78.save() 
GAMES79.save() 
GAMES80.save() 
GAMES81.save() 
GAMES82.save() 
GAMES83.save() 
GAMES84.save() 
GAMES85.save() 
GAMES86.save() 
GAMES87.save() 
GAMES88.save() 
GAMES89.save() 
GAMES90.save() 
GAMES91.save() 
GAMES92.save() 
GAMES93.save() 
GAMES94.save() 
GAMES95.save() 
GAMES96.save() 
GAMES97.save() 
GAMES98.save() 
GAMES99.save() 
GAMES100.save()
GAMES101.save()
GAMES102.save()
GAMES103.save()
GAMES104.save()
GAMES105.save()
GAMES106.save()
GAMES107.save()
GAMES108.save()
GAMES109.save()
GAMES110.save()
GAMES111.save()
GAMES112.save()
GAMES113.save()
GAMES114.save()
GAMES115.save()
GAMES116.save()
GAMES117.save()
GAMES118.save()
GAMES119.save()
GAMES120.save()
GAMES121.save()
GAMES122.save()
GAMES123.save()
GAMES124.save()
GAMES125.save()
GAMES126.save()
GAMES127.save()
GAMES128.save()
GAMES129.save()
GAMES130.save()
GAMES131.save()
GAMES132.save()
GAMES133.save()
GAMES134.save()
GAMES135.save()
GAMES136.save()
GAMES137.save()
GAMES138.save()
GAMES139.save()
GAMES140.save()
GAMES141.save()
GAMES142.save()
GAMES143.save()
GAMES144.save()
GAMES145.save()
GAMES146.save()
GAMES147.save()
GAMES148.save()
GAMES149.save()
GAMES150.save()
GAMES151.save()
GAMES152.save()
GAMES153.save()
GAMES154.save()
GAMES155.save()
GAMES156.save()
GAMES157.save()
GAMES158.save()
GAMES159.save()
GAMES160.save()
GAMES161.save()
GAMES162.save()
GAMES163.save()
GAMES164.save()
GAMES165.save()
GAMES166.save()
GAMES167.save()
GAMES168.save()
GAMES169.save()
GAMES170.save()
GAMES171.save()
GAMES172.save()
GAMES173.save()
GAMES174.save()
GAMES175.save()

app = Flask(__name__)

@app.route('/games', methods=['GET'])
@app.route('/games/<id>', methods=['GET'])
@app.route('/games/<name>', methods=['GET'])
def games(id=None, name=None):
    if id:
        games = Games.get(Games.id == id)
        games = model_to_dict(games)
        return jsonify(games)
    if name:
        title = Games.get(Games.name == name)
        title = model_to_dict(title)
        return jsonify(title)   
    else:
        game = []
        for games in Games.select():
            game.append(model_to_dict(games))
        return jsonify(game)


app.run(port=9000, debug=True)



